remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Arthur Reys
description: A summary of my work experience, research and publications.
logo: /assets/img/photo.jpg
is_user_page: true


linkedin: https://www.linkedin.com/in/arthur-reys-1580a11b4/