remote_theme: pages-themes/minimal@v0.2.0
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme

title: Arthur Reys
description: A summary of my work experience, research and publications.
logo: /assets/img/photo.jpg
is_user_page: true


linkedin: https://www.linkedin.com/in/arthur-reys-1580a11b4/
email: mailto:arthur.reys@gmail.com